sudo: false
language: go

go_import_path: gopkg.in/nabeken/aws-go-sqs.v1

go:
  - 1.5

before_script:
  - "mkdir $GOPATH/bin"
  - "curl -L http://projects.tsuntsun.net/~nabeken/golint-linux > $GOPATH/bin/golint"
  - "chmod u+x $GOPATH/bin/golint"

script:
  - go build ./...
  - golint ./...
  - go test -short -v ./...

after_script:
  - F=$(go fmt ./...); if [ ! -z "$F" ]; then echo "Please gofmt for"$'\n'"$F"; exit 1; fi
